return {
    base={
        box3={
            {
                {4,4,4,3,3,3,7,0,0,0},
                {4,1,6,6,2,3,7,0,0,0},
                {1,1,6,6,2,2,7,0,0,0},
                {1,7,7,7,7,2,7,0,0,0},
            },
            {
                {4,4,4,3,3,3,0,0,0,7},
                {4,1,6,6,2,3,0,0,0,7},
                {1,1,6,6,2,2,0,0,0,7},
                {1,7,7,7,7,2,0,0,0,7},
            },
            {
                {2,7,7,7,7,1,7,0,0,0},
                {2,2,6,6,1,1,7,0,0,0},
                {3,2,6,6,1,4,7,0,0,0},
                {3,3,3,4,4,4,7,0,0,0},
            },
            {
                {2,7,7,7,7,1,0,0,0,7},
                {2,2,6,6,1,1,0,0,0,7},
                {3,2,6,6,1,4,0,0,0,7},
                {3,3,3,4,4,4,0,0,0,7},
            },
        },
        pco3={
            {
                {1,1,0,0,0,0,7,3,3,3},
                {5,1,1,0,0,0,7,6,6,3},
                {5,5,2,2,0,0,7,6,6,4},
                {5,2,2,0,0,0,7,4,4,4},
            },
            {
                {1,1,0,0,0,0,7,4,4,4},
                {5,1,1,0,0,0,7,4,6,6},
                {5,5,2,2,0,0,7,3,6,6},
                {5,2,2,0,0,0,7,3,3,3},
            },
            {
                {3,3,3,1,7,1,0,0,0,0},
                {6,6,3,5,7,1,1,0,0,0},
                {6,6,4,5,7,5,2,2,0,0},
                {4,4,4,5,7,2,2,0,0,0},
            },
            {
                {4,4,4,1,7,1,0,0,0,0},
                {4,6,6,5,7,1,1,0,0,0},
                {3,6,6,5,7,5,2,2,0,0},
                {3,3,3,5,7,2,2,0,0,0},
            },
        },
        box4={
            {
                {4,4,4,3,3,3,0,0,0,0},
                {4,1,6,6,2,3,0,0,0,0},
                {1,1,6,6,2,2,0,0,0,0},
                {1,7,7,7,7,2,0,0,0,0},
            },
            {
                {2,7,7,7,7,1,0,0,0,0},
                {2,2,6,6,1,1,0,0,0,0},
                {3,2,6,6,1,4,0,0,0,0},
                {3,3,3,4,4,4,0,0,0,0},
            },
        },
        pco4={
            {
                {1,1,0,0,0,0,0,3,3,3},
                {5,1,1,0,0,0,0,6,6,3},
                {5,5,2,2,0,0,0,6,6,4},
                {5,2,2,0,0,0,0,4,4,4},
            },
            {
                {1,1,0,0,0,0,0,4,4,4},
                {5,1,1,0,0,0,0,4,6,6},
                {5,5,2,2,0,0,0,3,6,6},
                {5,2,2,0,0,0,0,3,3,3},
            },
            {
                {3,3,3,1,1,0,0,0,0,0},
                {6,6,3,5,1,1,0,0,0,0},
                {6,6,4,5,5,2,2,0,0,0},
                {4,4,4,5,2,2,0,0,0,0},
            },
            {
                {4,4,4,1,1,0,0,0,0,0},
                {4,6,6,5,1,1,0,0,0,0},
                {3,6,6,5,5,2,2,0,0,0},
                {3,3,3,5,2,2,0,0,0,0},
            },
        },
    },
    sequence={
        box3={'ZJJ','ZJL','ZTJ','JZJ','JZL','JSL','JJS','JJT','JJO','JJI','JLZ','JLT','JLO','JTJ','JTL','JTT','JOJ','JOL','JIJ','JIL','TJL','TJT','TTZ','TTJ','TIJ','OJJ','OJL','OOI','OIO','IJJ','IJL','ITJ','IOO'},
        pco3={'TJLL','TJII','TILL','JTLL','JLTL','JJIL','ITLL','ZTIL','ZSLT','ZLTT','ZLTS','ZLST','TZLT','TTLZ','TTLS','TTLL','TLTL','TLLT','TLLJ','TILO','TILJ','STLL','OILO','LZST','LTLT','LTII','LLJT','LLJO','LJLT','LJLO','LIJL','LIIT','JZLL','JZLJ','JZJL','JTTL','JTLT','JTII','JSTS','JSLL','JOLL','JLZJ','JLLT','JLLO','JLJI','JITI','JILJ','JIJL','ITLO','ITLJ','ITJL','ITIZ','IOLO','ILZT','ILTO','ILJL','ILIT','IJZT','IJTI','IJLL','IJJL','IJIT','IILT','ZZTS','ZZIL','ZTZS','ZTZJ','ZTTS','ZTSZ','ZTSJ','ZTOJ','ZTOI','ZTLZ','ZTLT','ZTLS','ZTLJ','ZTLI','ZTJZ','ZTJL','ZTIS','ZTIO','ZTII','ZSTZ','ZSTL','ZSIL','ZLZT','ZLTZ','ZLTL','ZLOT','ZLLJ','ZLJJ','ZJZS','ZJTS','ZJLL','ZJLJ','ZJJL','ZIZL','ZITO','ZITL','ZITJ','ZITI','ZISJ','ZIOL','ZILZ','ZILT','ZILI','ZIJZ','ZIIL','TZTS','TZTL','TZSJ','TZOJ','TZLZ','TZLS','TZLI','TZIS','TZIL','TTZS','TTZL','TTSZ','TTOI','TTLJ','TTJZ','TTJL','TTIO','TSZJ','TSTL','TSLT','TSJZ','TSJO','TSIZ','TOZJ','TOTI','TOOZ','TLZT','TLZI','TLTZ','TLTS','TLTJ','TLST','TLLZ','TLJZ','TLJT','TLJL','TLIZ','TJTL','TJTJ','TJSS','TJOO','TJLZ','TJLT','TJLJ','TJJZ','TJJL','TIZS','TIZL','TIZJ','TITI','TISZ','TIOL','TIOI','TILZ','TILS','TILI','TIJZ','TIJS','TIJO','TIJL','TIJI','TIIZ','TIIO','TIIL','TIIJ','SZTZ','SZLT','SZIL','STZZ','STLT','STJO','SLZT','SLLJ','SJTO','SIZL','SITT','SILZ','SIJI','SIIJ','OTOZ','OTJZ','OOTZ','OOLT','OOIL','OLOT','OLIT','OJLJ','OJJL','OIOL','OILZ','OILT','OILI','OIIL','LZZT','LZTZ','LZTT','LZTS','LZTI','LZOT','LZLJ','LZJL','LZJJ','LZIT','LTTL','LTLZ','LTLJ','LTJZ','LTJT','LSZT','LSLJ','LSJL','LOOT','LOLJ','LOJL','LLZJ','LLTZ','LLTJ','LLIJ','LJOL','LJLI','LJJT','LJIL','LIZT','LITO','LITI','LISZ','LIST','LIOT','LILJ','JZZS','JZTZ','JZTS','JZSZ','JZOT','JZOI','JZIO','JTZS','JTTZ','JTTO','JTTJ','JTSZ','JTSS','JTOT','JTOO','JTLZ','JTLJ','JTJZ','JTJT','JTJL','JSZT','JSTZ','JSST','JOZT','JOZI','JOTT','JOTO','JOOT','JOLJ','JOJL','JLTJ','JLSL','JLOL','JLOJ','JLJZ','JLJT','JLJS','JLJO','JLIJ','JJZL','JJTZ','JJTL','JJOL','JJLZ','JJLT','JJLS','JJLO','JJLI','JIZT','JITZ','JITS','JIST','JIOT','JIIT','IZZL','IZTO','IZTL','IZTJ','IZTI','IZSJ','IZOL','IZLZ','IZLT','IZLI','IZJZ','IZIL','ITZS','ITZO','ITZL','ITZJ','ITZI','ITTI','ITSZ','ITOL','ITOI','ITLZ','ITLS','ITLI','ITJZ','ITJS','ITJO','ITJI','ITIO','ITIL','ITIJ','ISZL','ISZJ','ISTT','ISLZ','ISJI','ISIJ','IOZL','IOTL','IOOL','IOLZ','IOLT','IOLI','IOIL','ILTZ','ILTS','ILTI','ILSZ','ILST','ILOT','ILLJ','IJTZ','IJTS','IJTO','IJTL','IJST','IJSI','IJOZ','IJOT','IJLJ','IJIS','IJIO','IIZL','IITZ','IITO','IITL','IITJ','IISJ','IIOL','IIOJ','IIJO'},
        box4={'ZZJL','ZZLJ','ZSTJ','ZSTL','ZJLI','ZJTT','ZJIJ','ZJIL','ZLZL','ZLLO','ZTSJ','ZTJS','ZTJT','ZTLI','ZTTS','ZTTL','ZTIJ','ZTIL','ZOJJ','ZOTJ','ZIJJ','ZIJL','ZITJ','ZITL','JZJI','JZLI','JZTT','JZOJ','JZIJ','JZIL','JSSJ','JSJS','JSJO','JSLT','JSLI','JSTT','JSOJ','JSOL','JSIL','JJZT','JJSO','JJSI','JJLL','JJTL','JJOZ','JJOO','JJOI','JJIS','JJIT','JJIO','JJII','JLZS','JLZT','JLZI','JLSZ','JLST','JLSI','JLJL','JLLJ','JLTJ','JLTL','JLTI','JLOZ','JLOS','JLOI','JLIZ','JLIS','JLIT','JLIO','JTZS','JTSJ','JTST','JTJS','JTJL','JTLJ','JTLO','JTLI','JTTI','JTOL','JTIJ','JTIL','JTIT','JOZJ','JOSJ','JOSL','JOJZ','JOJT','JOJO','JOJI','JOLS','JOLI','JOTL','JOOJ','JOOL','JOIJ','JOIL','JIZJ','JIZL','JISL','JIJS','JIJT','JIJO','JIJI','JILZ','JILS','JILT','JILO','JITJ','JITL','JITT','JIOJ','JIOL','JIIJ','JIIL','TZSJ','TZJS','TZJL','TZLZ','TZLI','TZTL','TZIL','TJZS','TJZL','TJST','TJJL','TJJO','TJLJ','TJTS','TJTL','TJTI','TJIL','TJIT','TTZS','TTZL','TTJS','TTJJ','TTJL','TTJI','TTOJ','TTOI','TTIZ','TTIJ','TTIO','TOJT','TOJO','TOJI','TOTJ','TOOJ','TOIJ','TIZL','TIJL','TIJT','TITZ','TITJ','TITO','TIOJ','TIIJ','OZJJ','OJJT','OJJO','OJJI','OJLI','OJOJ','OJOL','OJIJ','OJIL','OTJT','OTJO','OTJI','OTOJ','OTIJ','OOJJ','OOJL','OOTJ','OOII','OIJJ','OIJL','OITJ','OIOI','OIIO','IZJJ','IZJL','IZTJ','IZTL','IJZJ','IJZL','IJSL','IJJS','IJJT','IJJO','IJJI','IJLZ','IJLS','IJLT','IJLO','IJTJ','IJTL','IJTT','IJOJ','IJOL','IJIJ','IJIL','ITZL','ITJL','ITJT','ITTZ','ITTJ','ITTO','ITOJ','ITIJ','IOJJ','IOJL','IOTJ','IOOI','IOIO','IIJJ','IIJL','IITJ','IIOO'},
        pco4={},
    },
}
