local baseDict={
    {'intro: aboutDict'},
    {'intro: setting_out',hidden=true},
    {'guide: noobGuide'},
    {'guide: keybinding'},
    {'guide: handling'},
    {'term1: field'},
    {'term1: piece'},
    {'term1: clear'},
    {'term1: clear_big',hidden=function() return false end},
    {'term1: clear_huge',hidden=function() return false end},
    {'term1: next'},
    {'term1: hold'},
    {'term2: combo'},
    {'term2: rotation_system'},
    {'term2: spin'},
    {'term2: all_clear'},
    {'term2: charge'},
    {'term2: sequence'},
    {'term2: tuning'},
    {'term2: buffered_input'},
    {'term2: gravity'},
    {'term2: delays'},
    {'term2: death_condition'},
    {'term3: invisible'},
    {'term3: chain'},
    {'term3: spike'},
    {'term3: speeds'},
    {'term3: misaction'},
    {'term3: finesse'},
    {'other: 26f_studio'},
}

return baseDict
