name: "Build Android"
description: "Build Android package"
inputs:
  type:
    required: true
    description: "snapshot or release"
  apkCode:
    required: true
    description: "apk code"
  name:
    required: true
    description: "name of the product"
  output:
    required: true
    description: 'Output path and name of the product'
  ANDROID_KEYSTORE_ALIAS:
    required: true
    description: "Signing keystore's alias"
  ANDROID_KEYSTORE_BASE64:
    required: true
    description: "Signing keystore's base64 content"
  ANDROID_KEYSTORE_KEYPASSWORD:
    required: true
    description: "Signing keystore's key password"
  ANDROID_KEYSTORE_STOREPASSWORD:
    required: true
    description: "Signing keystore's keystore password"

runs:
  using: "composite"
  steps:
    - name: Get Java
      uses: actions/setup-java@v2
      with:
        distribution: "adopt"
        java-version: "11"
    - name: Clone love-android
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/love2d/love-android -b 11.4 --depth 1 --shallow-submodules
    - name: Copy resources
      shell: bash
      run: |
        cp -r -f ./.github/build/Android/res/* ./love-android/app/src/main/res/
        cp -r -f ./assets/ ./Zenitha/ ./conf.lua ./main.lua ./version.lua ./love-android/app/src/embed/assets/
    - name: Update android information
      shell: python
      run: |
        if '${{ inputs.type }}' == 'release':
          appName = 'Techmino Galaxy'
          packageName = 'org.f26_studio.techmino_galaxy'
          edition = 'release'
        elif '${{ inputs.type }}' == 'snapshot':
          appName = 'Techmino Galaxy Snapshot'
          packageName = 'org.f26_studio.techmino_galaxy.snapshot'
          edition = 'snapshot'
        with open('./love-android/app/src/main/AndroidManifest.xml', "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('LÖVE for Android', appName)\
            .replace('@drawable/love', f'@mipmap/{edition}')
          file.seek(0)
          file.truncate()
          file.write(data)
        with open("./love-android/app/build.gradle", "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('org.love2d.android', packageName)\
            .replace('30', '${{ inputs.apkCode }}')\
            .replace('11.4', '${{ inputs.name }}')
          insert_pos = data.find('\n', data.find('proguardFiles')) + 1
          data = data[:insert_pos] + '            signingConfig signingConfigs.release\n' + data[insert_pos:]
          insert_pos = data.find('buildTypes') - 4
          data = data[:insert_pos] + "    signingConfigs {\n" \
                                   "        release {\n" \
                                   "            storeFile file('./android.keystore')\n" \
                                   "            keyAlias '${{ inputs.ANDROID_KEYSTORE_ALIAS }}'\n" \
                                   "            keyPassword '${{ inputs.ANDROID_KEYSTORE_KEYPASSWORD }}'\n" \
                                   "            storePassword '${{ inputs.ANDROID_KEYSTORE_STOREPASSWORD }}'\n" \
                                   "        }\n" \
                                   "    }\n" + data[insert_pos:]
          file.seek(0)
          file.truncate()
          file.write(data)
    - name: Build Techmino Galaxy
      shell: bash
      run: |
        echo "${{ inputs.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > ./love-android/app/android.keystore
        cd ./love-android/
        chmod +x ./gradlew
        ./gradlew assembleEmbedRecordRelease
    - name: Rename APK
      shell: bash
      run: mv ./love-android/app/build/outputs/apk/embedRecord/release/app-embed-record-release.apk ${{ inputs.output }}
