name: 'build Android'
description: 'build Android package'
inputs:
  type:
    required: true
    description: 'snapshot or release'
  apkCode:
    required: true
    description: 'apk code'
  name:
    required: true
    description: 'name of the product'
  file-path:
    required: true
    description: 'path to the product'
  SIGNING_KEY:
    required: true
    description: 'APK signing key'
  KEY_STORE_PASSWORD:
    required: true
    description: 'APK key store password'
  ALIAS:
    required: true
    description: 'APK key alias'
  KEY_PASSWORD:
    required: true
    description: 'APK key password'
runs:
  using: "composite"
  steps:
    - name: Get Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Clone love-android
      shell: bash
      run: |
        git clone --recurse-submodules https://github.com/love2d/love-android -b 11.4 --depth 1 --shallow-submodules
    - name: Copy Resources
      shell: bash
      run: |
        cp -r -f ./.github/build/Android/res/* ./love-android/app/src/main/res/
        cp -r -f ./assets/ ./Zenitha/ conf.lua main.lua version.lua ./love-android/app/src/embed/assets/
    - name: update Android information
      shell: python
      run: |
        if '${{ inputs.type }}' == 'release':
          appName = 'Techmino Galaxy'
          packageName = 'org.f26_studio.techmino_galaxy'
          edition = 'release'
        elif '${{ inputs.type }}' == 'snapshot':
          appName = 'Techmino Galaxy Snapshot'
          packageName = 'org.f26_studio.techmino_galaxy.snapshot'
          edition = 'snapshot'
        with open('./love-android/app/src/main/AndroidManifest.xml', "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('LÖVE for Android', appName)\
            .replace('@drawable/love', f'@mipmap/{edition}')
          file.seek(0)
          file.truncate()
          file.write(data)
        with open("./love-android/app/build.gradle", "r+", encoding='utf-8') as file:
          data = file.read()
          data = data\
            .replace('org.love2d.android', packageName)\
            .replace('30', '${{ inputs.apkCode }}')\
            .replace('11.4', '${{ inputs.name }}')
          insert_pos = data.find('\n', data.find('proguardFiles')) + 1
          data = data[:insert_pos] + '            signingConfig signingConfigs.release\n' + data[insert_pos:]
          insert_pos = data.find('buildTypes') - 4
          data = data[:insert_pos] + "    signingConfigs {\n" \
                                   "        release {\n" \
                                   "            storeFile file('./android.keystore')\n" \
                                   "            storePassword '${{ inputs.KEY_STORE_PASSWORD }}'\n" \
                                   "            keyAlias '${{ inputs.ALIAS }}'\n" \
                                   "            keyPassword '${{ inputs.KEY_PASSWORD }}'\n" \
                                   "        }\n" \
                                   "    }\n" + data[insert_pos:]
          file.seek(0)
          file.truncate()
          file.write(data)
    - name: Build Techmino
      shell: bash
      run: |
        echo "${{ inputs.SIGNING_KEY }}" | base64 -d > love-android/app/android.keystore
        cd love-android/
        chmod +x ./gradlew
        ./gradlew assembleEmbedRecordRelease
    - name: rename apk
      shell: bash
      run: mv love-android/app/build/outputs/apk/embedRecord/release/app-embed-record-release.apk ${{ inputs.file-path }}
