return {
    initialize=function()
        GAME.newPlayer(1,'mino')
        GAME.setMain(1)
        playBgm('race','base')
    end,
    settings={mino={
        event={
            playerInit={
                mechLib.mino.statistics.event_playerInit,
                "P:addEvent('afterClear',mechLib.mino.progress.sprint_200_afterClear)",
            },
            afterClear={
                mechLib.mino.statistics.event_afterClear,
                mechLib.mino.sprint.event_afterClear[200],
            },
            drawInField=mechLib.mino.sprint.event_drawInField[200],
            drawOnPlayer=mechLib.mino.sprint.event_drawOnPlayer[200],
        },
    }},
}
