return {
    initialize=function()
        GAME.newPlayer(1,'mino')
        GAME.setMain(1)
        playBgm('race','base')
    end,
    settings={mino={
        pieceVisTime=120,
        pieceFadeTime=120,
        event={
            playerInit={
                mechLib.mino.statistics.event_playerInit,
                mechLib.mino.misc.coverField_switch_auto,
                "P:addEvent('afterClear',mechLib.mino.progress.sprint_blind_40_afterClear)",
            },
            afterClear={
                mechLib.mino.statistics.event_afterClear,
                mechLib.mino.sprint.event_afterClear[40],
            },
            drawInField={
                mechLib.mino.sprint.event_drawInField[40],
            },
            drawOnPlayer=mechLib.mino.sprint.event_drawOnPlayer[40],
        },
    }},
}
