return {
    initialize=function()
        GAME.newPlayer(1,'mino')
        GAME.setMain(1)
        playBgm('race','base')
    end,
    settings={mino={
        event={
            playerInit={
                mechLib.mino.statistics.event_playerInit,
                mechLib.mino.misc.obstacle_generateField,
                "P:addEvent('afterClear',mechLib.mino.progress.sprint_obstacle_20_afterClear)",
            },
            afterClear=mechLib.mino.misc.obstacle_event_afterClear[20],
            drawInField=mechLib.mino.sprint.event_drawInField[20],
            drawOnPlayer=mechLib.mino.sprint.event_drawOnPlayer[20],
        },
    }},
}
