name: Techmino Galaxy Develop CI

on:
  push:
    branches: [main, ci*, remote*]
  pull_request:
    branches: [main]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      versionName: ${{ steps.info.outputs.versionName }}
      versionString: ${{ steps.info.outputs.versionString }}
      versionCode: ${{ steps.info.outputs.versionCode }}
      commitHash: ${{ steps.info.outputs.commitHash }}
    steps:
      - uses: actions/checkout@v3
      - name: Install lua
        run: |
          sudo apt-get install lua5.3 -y
      - name: Get app info
        id: info
        run: |
          echo "::set-output name=versionName::$(lua ./.github/workflows/getVersion.lua -versionName)"
          echo "::set-output name=versionString::$(lua ./.github/workflows/getVersion.lua -versionString)"
          echo "::set-output name=versionCode::$(lua ./.github/workflows/getVersion.lua -versionCode)"
          echo "::set-output name=commitHash::$(git rev-parse --short ${{ GITHUB.SHA }})"

  remote-ci:
    runs-on: ubuntu-latest
    needs: get-info
    steps:
      - name: Remote CI
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          owner: 26F-Studio
          repo: 26F-CI
          workflow_file_name: dev.yml
          client_payload: '{
            "repository": "${{ github.repository }}",
            "buildType": "dev",
            "buildList": "./assets/ ./Zenitha/ ./conf.lua ./main.lua ./version.lua",
            "packageName": "Techmino_Galaxy_${{ needs.get-info.outputs.versionName }}_${{ needs.get-info.outputs.commitHash }}_#${{ GITHUB.RUN_NUMBER }}",
            "versionName": "${{ needs.get-info.outputs.versionName }}",
            "versionString": "${{ needs.get-info.outputs.versionString }}",
            "versionCode": "${{ needs.get-info.outputs.versionCode }}"
            }'
