name: Techmino Galaxy Develop CI

on:
  push:
    branches: [main, ci*]
  pull_request:
    branches: [main]

jobs:
  get-info:
    runs-on: ubuntu-latest
    outputs:
      app-name: ${{ steps.app-info.outputs.app-name }}
      bundle-id: ${{ steps.app-info.outputs.bundle-id }}
      version-name: ${{ steps.app-info.outputs.version-name }}
      version-string: ${{ steps.app-info.outputs.version-string }}
      version-code: ${{ steps.app-info.outputs.version-code }}
      commit-hash: ${{ steps.git-info.outputs.commit-hash }}
    steps:
      - uses: actions/checkout@v3
      - name: Install lua
        run: |
          sudo apt-get install lua5.3 -y
      - name: Get app info
        id: app-info
        shell: lua {0}
        run: |
          local version = require 'version'
          print('::set-output name=app-name::'..version.appName)
          print('::set-output name=bundle-id::org.f26_studio.'..version.appName:gsub('[^A-Za-z0-9]+', '_'))
          print('::set-output name=version-name::'..version.appVer)
          print('::set-output name=version-string::'..version.verStr)
          print(('::set-output name=version-code::%d'):format(version.apkCode))
      - name: Get git info
        id: git-info
        shell: bash
        run: |
          commitHash=$(git rev-parse --short ${{ GITHUB.SHA }})
          echo '::set-output name=commitHash::$commitHash'

  build-android:
    runs-on: ubuntu-latest
    needs: get-info
    env:
      BARE_PACKAGE_PATH: "./target.love"
    steps:
      - uses: actions/checkout@v3
      - name: Build bare love package
        uses: 26F-Studio/love-actions-core@v1.0.1
        with:
          build-list: ./assets/ ./Zenitha/ ./conf.lua ./main.lua ./version.lua
          package-path: ${{ env.BARE_PACKAGE_PATH }}
      - name: Build love android
        id: build-love
        uses: 26F-Studio/love-actions-android@v1.0.0
        with:
          app-name: ${{ needs.get-info.outputs.app-name }}
          bundle-id: ${{ needs.get-info.outputs.bundle-id }}
          keystore-alias: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          keystore-base64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          keystore-key-password: ${{ secrets.ANDROID_KEYSTORE_KEYPASSWORD }}
          keystore-store-password: ${{ secrets.ANDROID_KEYSTORE_STOREPASSWORD }}
          love-package: ${{ env.BARE_PACKAGE_PATH }}
          resource-path: ./.github/build/android/dev/res
          version-string: ${{ needs.get-info.outputs.version-string }}
          version-code: ${{ needs.get-info.outputs.version-code }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Techmino_Galaxy_${{ needs.get-info.outputs.version-string }}_${{ needs.get-info.outputs.commit-hash }}_#${{ GITHUB.RUN_NUMBER }}_Android
          path: ${{ steps.build-love.outputs.package-paths }}